# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/zz/xilinx/frequency-divider/src/pin_con/ad9226_pin.xdc

# XDC: /home/zz/xilinx/frequency-divider/src/pin_con/spi_pin.xdc

# XDC: /home/zz/xilinx/frequency-divider/src/pin_con/startspeedup.xdc

# XDC: /home/zz/xilinx/frequency-divider/src/pin_con/top_pins.xdc

# XDC: new/debug_chouse.xdc

# IP: ip/fir_compiler_high/fir_compiler_high.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_compiler_high || ORIG_REF_NAME==fir_compiler_high} -quiet] -quiet

# IP: ip/fir_compiler_low/fir_compiler_low.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_compiler_low || ORIG_REF_NAME==fir_compiler_low} -quiet] -quiet

# IP: ip/dds_compiler_2k/dds_compiler_2k.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_2k || ORIG_REF_NAME==dds_compiler_2k} -quiet] -quiet

# XDC: ip/fir_compiler_high/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_compiler_high || ORIG_REF_NAME==fir_compiler_high} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/fir_compiler_low/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_compiler_low || ORIG_REF_NAME==fir_compiler_low} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
